# This is a randomizer file for the Simple Randomizer Maker.
# This file must be named randomizer.py in order to work.

from classes import *

def value(name):
	for att in Attributes:
		if att.name == name:
			return att
	print("This attribute does not exist: "+name)
	return None

########################
# EDIT BELOW THIS LINE #
########################

Program_Name = "Megaman: Wily Wars Randomizer"
Rom_Name = "Megaman The Wily Wars"
Rom_File_Format = ""
About_Page_Text = "2021 MaximumLance. Thanks to Runex, Matrixz, MottZilla, and GateGuy."
Timeout = 15
Slow_Mode = False

"""
If you're using this file as a template, MAKE SURE YOU DELETE THESE ATTRIBUTES!
"""
Attributes = [

        Attribute(
		name="1st stage",
		addresses=[0x644C2],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
	Attribute(
		name="2nd stage",
		addresses=[0x644C3],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="3rd stage",
		addresses=[0x644C4],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="4th stage",
		addresses=[0x644C5],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="5th stage",
		addresses=[0x644C6],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="6th stage",
		addresses=[0x644C7],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="7th stage",
		addresses=[0x644C8],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="8th stage",
		addresses=[0x644C9],
		number_of_bytes=1,
		possible_values=[0,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
 
        Attribute(
                name="Doc Robot 1 Programming",
		addresses=[0x7B7F3],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 2 Programming",
		addresses=[0x7B8DF],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 3 Programming",
		addresses=[0x7BA41],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 4 Programming",
		addresses=[0x7BC11],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 5 Programming",
		addresses=[0x7BDF9],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 6 Programming",
		addresses=[0x7BF1B],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Robot 7 Programming",
		addresses=[0x7C0DB],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 8 Programming",
		addresses=[0x7C1C7],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 1",
		addresses=[0x85810],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 2",
		addresses=[0x85811],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 3",
		addresses=[0x85812],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 4",
		addresses=[0x85813],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 5",
		addresses=[0x85814],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 6",
		addresses=[0x85815],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 7",
		addresses=[0x85816],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 8",
		addresses=[0x85817],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 2 Weakness 1",
		addresses=[0x85820],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 2",
		addresses=[0x85821],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 3",
		addresses=[0x85822],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 4",
		addresses=[0x85823],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 5",
		addresses=[0x85824],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 6",
		addresses=[0x85825],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 7",
		addresses=[0x85826],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 8",
		addresses=[0x85827],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 3 Weakness 1",
		addresses=[0x85830],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 2",
		addresses=[0x85831],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 3",
		addresses=[0x85832],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 4",
		addresses=[0x85833],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 5",
		addresses=[0x85834],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 6",
		addresses=[0x85835],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 7",
		addresses=[0x85836],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 8",
		addresses=[0x85837],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 4 Weakness 1",
		addresses=[0x85840],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 2",
		addresses=[0x85841],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 3",
		addresses=[0x85842],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 4",
		addresses=[0x85843],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 5",
		addresses=[0x85844],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 6",
		addresses=[0x85845],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 7",
		addresses=[0x85846],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 8",
		addresses=[0x85847],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 5 Weakness 1",
		addresses=[0x85850],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 2",
		addresses=[0x85851],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 3",
		addresses=[0x85852],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 4",
		addresses=[0x85853],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 5",
		addresses=[0x85854],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 6",
		addresses=[0x85855],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 7",
		addresses=[0x85856],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 8",
		addresses=[0x85857],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 6 Weakness 1",
		addresses=[0x85860],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 2",
		addresses=[0x85861],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 3",
		addresses=[0x85862],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 4",
		addresses=[0x85863],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 5",
		addresses=[0x85864],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 6",
		addresses=[0x85865],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 7",
		addresses=[0x85866],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 8",
		addresses=[0x85867],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 7 Weakness 1",
		addresses=[0x85870],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 2",
		addresses=[0x85871],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 3",
		addresses=[0x85872],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 4",
		addresses=[0x85873],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 5",
		addresses=[0x85874],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 6",
		addresses=[0x85875],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 7",
		addresses=[0x85876],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 8",
		addresses=[0x85877],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 8 Weakness 1",
		addresses=[0x85880],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 2",
		addresses=[0x85881],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 3",
		addresses=[0x85882],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 4",
		addresses=[0x85883],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 5",
		addresses=[0x85884],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 6",
		addresses=[0x85885],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 7",
		addresses=[0x85886],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 8",
		addresses=[0x85887],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 1",
		addresses=[0x85890],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 2",
		addresses=[0x85891],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 3",
		addresses=[0x85892],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 4",
		addresses=[0x85893],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 5",
		addresses=[0x85894],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 6",
		addresses=[0x85895],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 7",
		addresses=[0x85896],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 8",
		addresses=[0x85897],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 2 Weakness 1",
		addresses=[0x858A0],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 2",
		addresses=[0x858A1],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 3",
		addresses=[0x858A2],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 4",
		addresses=[0x858A3],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 5",
		addresses=[0x858A4],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 6",
		addresses=[0x858A5],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 7",
		addresses=[0x858A6],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 8",
		addresses=[0x858A7],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 3 Weakness 1",
		addresses=[0x858B0],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 2",
		addresses=[0x858B1],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 3",
		addresses=[0x858B2],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 4",
		addresses=[0x858B3],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 5",
		addresses=[0x858B4],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 6",
		addresses=[0x858B5],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 7",
		addresses=[0x858B6],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 8",
		addresses=[0x858B7],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 4 Weakness 1",
		addresses=[0x858C0],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 2",
		addresses=[0x858C1],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 3",
		addresses=[0x858C2],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 4",
		addresses=[0x858C3],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 5",
		addresses=[0x858C4],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 6",
		addresses=[0x858C5],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 7",
		addresses=[0x858C6],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 8",
		addresses=[0x858C7],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 5 Weakness 1",
		addresses=[0x858D0],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 2",
		addresses=[0x858D1],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 3",
		addresses=[0x858D2],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 4",
		addresses=[0x858D3],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 5",
		addresses=[0x858D4],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 6",
		addresses=[0x858D5],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 7",
		addresses=[0x858D6],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 8",
		addresses=[0x858D7],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 6 Weakness 1",
		addresses=[0x858E0],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 2",
		addresses=[0x858E1],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 3",
		addresses=[0x858E2],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 4",
		addresses=[0x858E3],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 5",
		addresses=[0x858E4],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 6",
		addresses=[0x858E5],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 7",
		addresses=[0x858E6],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 8",
		addresses=[0x858E7],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 7 Weakness 1",
		addresses=[0x858F0],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 2",
		addresses=[0x858F1],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 3",
		addresses=[0x858F2],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 4",
		addresses=[0x858F3],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 5",
		addresses=[0x858F4],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 6",
		addresses=[0x858F5],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 7",
		addresses=[0x858F6],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 8",
		addresses=[0x858F7],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 8 Weakness 1",
		addresses=[0x85900],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 2",
		addresses=[0x85901],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 3",
		addresses=[0x85902],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 4",
		addresses=[0x85903],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 5",
		addresses=[0x85904],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 6",
		addresses=[0x85905],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 7",
		addresses=[0x85906],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 8",
		addresses=[0x85907],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 1",
		addresses=[0x85910],
		number_of_bytes=1,
                possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 2",
		addresses=[0x85911],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 3",
		addresses=[0x85912],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 4",
		addresses=[0x85913],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 5",
		addresses=[0x85914],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 6",
		addresses=[0x85915],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 7",
		addresses=[0x85916],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 8",
		addresses=[0x85917],
		number_of_bytes=1,
		possible_values=[0x82,1,3],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Yellow Devil Mk-3 Weakness 1",
		addresses=[0x85920],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 2",
		addresses=[0x85921],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 3",
		addresses=[0x85922],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 4",
		addresses=[0x85923],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 5",
		addresses=[0x85924],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 6",
		addresses=[0x85925],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 7",
		addresses=[0x85926],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 8",
		addresses=[0x85927],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Holograph Megamans Weakness 1",
		addresses=[0x85930],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 2",
		addresses=[0x85931],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 3",
		addresses=[0x85932],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 4",
		addresses=[0x85933],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 5",
		addresses=[0x85934],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 6",
		addresses=[0x85935],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 7",
		addresses=[0x85936],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 8",
		addresses=[0x85937],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Wily Machine 3-1 Weakness 1",
		addresses=[0x85940],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 2",
		addresses=[0x85941],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 3",
		addresses=[0x85942],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 4",
		addresses=[0x85943],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 5",
		addresses=[0x85944],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 6",
		addresses=[0x85945],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 7",
		addresses=[0x85946],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-1 Weakness 8",
		addresses=[0x85947],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Wily Machine 3-2 Weakness 1",
		addresses=[0x85950],
		number_of_bytes=1,
                possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 2",
		addresses=[0x85951],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 3",
		addresses=[0x85952],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 4",
		addresses=[0x85953],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 5",
		addresses=[0x85954],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 6",
		addresses=[0x85955],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 7",
		addresses=[0x85956],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3-2 Weakness 8",
		addresses=[0x85957],
		number_of_bytes=1,
		possible_values=[0x82,1,2,4,7],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Gamma 1 Weakness 1",
		addresses=[0x85960],
		number_of_bytes=1,
                possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 2",
		addresses=[0x85961],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 3",
		addresses=[0x85962],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 4",
		addresses=[0x85963],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 5",
		addresses=[0x85964],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 6",
		addresses=[0x85965],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 7",
		addresses=[0x85966],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 8",
		addresses=[0x85967],
		number_of_bytes=1,
		possible_values=[0x82,2,4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Gamma 2 Weakness 1",
		addresses=[0x85970],
		number_of_bytes=1,
                possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 2",
		addresses=[0x85971],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 3",
		addresses=[0x85972],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 4",
		addresses=[0x85973],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 5",
		addresses=[0x85974],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 6",
		addresses=[0x85975],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 7",
		addresses=[0x85976],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 8",
		addresses=[0x85977],
		number_of_bytes=1,
		possible_values=[0x82,2,3],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boobeam Weakness 2",
		addresses=[0x85981],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Alien Weakness 1",
		addresses=[0x85982],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Alien Weakness 2",
		addresses=[0x85983],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Random Boss 1",
		addresses=[0x85990],
		number_of_bytes=1,
                possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 2",
		addresses=[0x85991],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 3",
		addresses=[0x85992],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 4",
		addresses=[0x85993],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 5",
		addresses=[0x85994],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 6",
		addresses=[0x85995],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 7",
		addresses=[0x85996],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 8",
		addresses=[0x85997],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 1",
		addresses=[0x859A0],
		number_of_bytes=1,
                possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 2",
		addresses=[0x859A1],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 3",
		addresses=[0x859A2],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 4",
		addresses=[0x859A3],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 5",
		addresses=[0x859A4],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 6",
		addresses=[0x859A5],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 7",
		addresses=[0x859A6],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 8",
		addresses=[0x859A7],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Flag 1",
		addresses=[0x85800],
		number_of_bytes=1,
		min_value=0,
		max_value=255,
	),
        Attribute(
                name="Random Flag 2",
		addresses=[0x85801],
		number_of_bytes=1,
		min_value=0,
		max_value=255,
	),
        Attribute(
                name="Random Flag 3",
		addresses=[0x85802],
		number_of_bytes=1,
		min_value=0,
		max_value=255,
	),
        Attribute(
                name="Random Flag 4",
		addresses=[0x85803],
		number_of_bytes=1,
		min_value=0,
		max_value=255,
	),
        Attribute(
                name="Random Flag 5",
		addresses=[0x85804],
		number_of_bytes=1,
		min_value=0,
		max_value=255,
	),
        Attribute(
                name="Rush Marine Flag",
		addresses=[0x85805],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Rush Jet Flag",
		addresses=[0x85806],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Item 3 Flag",
		addresses=[0x8580D],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Sparkman Capsule",
		addresses=[0x859B0],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Snakeman Capsule",
		addresses=[0x859B1],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Needleman Capsule",
		addresses=[0x859B2],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Hardman Capsule",
		addresses=[0x859B3],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Topman Capsule",
		addresses=[0x859B4],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Geminiman Capsule",
		addresses=[0x859B5],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Magnetman Capsule",
		addresses=[0x859B6],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Shadowman Capsule",
		addresses=[0x859B7],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
         Attribute(
                name="Random Weapon Breaks walls",
		addresses=[0x85807],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Random Weapon Breaks walls 2",
		addresses=[0x85808],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Random Weapon Breaks walls 3",
		addresses=[0x85809],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Boss affected by Flash Stopper 1",
		addresses=[0x8580A],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Boss affected by Flash Stopper 2",
		addresses=[0x8580B],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Robot affected by Flash Stopper",
		addresses=[0x8563B],
                number_of_bytes=1,
                possible_values=[0x7C,0xA9,0xAB,0xAD,0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
         Attribute(
                name="Boss affected by Flash Stopper 3",
		addresses=[0x8580C],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Boss 1 Buster Damage",
		addresses=[0x859C0],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 2 Buster Damage",
		addresses=[0x859C1],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 3 Buster Damage",
		addresses=[0x859C2],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 4 Buster Damage",
		addresses=[0x859C3],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 5 Buster Damage",
		addresses=[0x859C4],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 6 Buster Damage",
		addresses=[0x859C5],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 7 Buster Damage",
		addresses=[0x859C6],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 8 Buster Damage",
		addresses=[0x859C7],
                number_of_bytes=1,
		min_value=1,
		max_value=3,
	),
        Attribute(
                name="Boss 1 Collision Damage",
		addresses=[0x859D0],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 2 Collision Damage",
		addresses=[0x859D1],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 3 Collision Damage",
		addresses=[0x859D2],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 4 Collision Damage",
		addresses=[0x859D3],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 5 Collision Damage",
		addresses=[0x859D4],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 6 Collision Damage",
		addresses=[0x859D5],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 7 Collision Damage",
		addresses=[0x859D6],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 8 Collision Damage",
		addresses=[0x859D7],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Metal Collision Damage",
		addresses=[0x859D8],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Heat Collision Damage",
		addresses=[0x859D9],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Quick Collision Damage",
		addresses=[0x859DA],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Air Collision Damage",
		addresses=[0x859DB],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Crash Collision Damage",
		addresses=[0x859DC],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Flash Collision Damage",
		addresses=[0x859DD],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Bubble Collision Damage",
		addresses=[0x859DE],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Wood Collision Damage",
		addresses=[0x859DF],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Breakman Collision Damage",
		addresses=[0x859E0],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Kame Maker Collision Damage",
		addresses=[0x859E1],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Yellow Devil 2 Collision Damage",
		addresses=[0x859E2],
                number_of_bytes=1,
		min_value=2,
		max_value=6,
	),
        Attribute(
                name="Holograph Megamans Collision Damage",
		addresses=[0x859E3],
                number_of_bytes=1,
		min_value=2,
		max_value=6,
	),
        Attribute(
                name="Wily Machine 3-1 Collision Damage",
		addresses=[0x859E4],
                number_of_bytes=1,
		min_value=3,
		max_value=6,
	),
        Attribute(
                name="Wily Machine 3-2 Collision Damage",
		addresses=[0x859E5],
                number_of_bytes=1,
		min_value=3,
		max_value=6,
	),
        Attribute(
                name="Boss 1 Weapon Damage",
		addresses=[0x859F0],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 2 Weapon Damage",
		addresses=[0x859F1],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 3 Weapon Damage",
		addresses=[0x859F2],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 4 Weapon Damage",
		addresses=[0x859F3],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 5 Weapon Damage",
		addresses=[0x859F4],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 6 Weapon Damage",
		addresses=[0x859F5],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 7 Weapon Damage",
		addresses=[0x859F6],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boss 8 Weapon Damage",
		addresses=[0x859F7],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Metal Weapon Damage",
		addresses=[0x859F8],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Heat Weapon Damage",
		addresses=[0x859F9],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Quick Weapon Damage",
		addresses=[0x859FA],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Air Weapon Damage",
		addresses=[0x859FB],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Crash Weapon Damage",
		addresses=[0x859FC],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Bubble Weapon Damage",
		addresses=[0x859FD],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Doc Wood Weapon Damage",
		addresses=[0x859FE],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Breakman Weapon Damage",
		addresses=[0x859FF],
                number_of_bytes=1,
		min_value=2,
		max_value=5,
	),
        Attribute(
                name="Wily Machine 3 Weapon Damage",
		addresses=[0x85A00],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Gamma 1 Weapon Damage",
		addresses=[0x85A01],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Gamma 2 Weapon Damage",
		addresses=[0x85A02],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Mecha Dragon Weapon Damage",
		addresses=[0x85A03],
                number_of_bytes=1,
		min_value=4,
		max_value=8,
	),
        Attribute(
                name="Guts Tank Weapon Damage",
		addresses=[0x85A04],
                number_of_bytes=1,
		min_value=2,
		max_value=7,
	),
        Attribute(
                name="Boobeam Weapon Damage",
		addresses=[0x85A05],
                number_of_bytes=1,
		min_value=2,
		max_value=6,
	),
        Attribute(
                name="Wily Machine 2-1 Weapon Damage",
		addresses=[0x85A06],
                number_of_bytes=1,
		min_value=2,
		max_value=4,
	),
        Attribute(
                name="Wily Machine 2-2 Weapon Damage",
		addresses=[0x85A07],
                number_of_bytes=1,
		min_value=4,
		max_value=8,
	),
        Attribute(
                name="Alien Weapon Damage",
		addresses=[0x85A08],
                number_of_bytes=1,
		min_value=4,
		max_value=8,
        ),
        Attribute(
                name="Weapon 1 Ammo Usage",
		addresses=[0x85A10],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 2 Ammo Usage",
		addresses=[0x85A11],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 3 Ammo Usage",
		addresses=[0x85A12],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 4 Ammo Usage",
		addresses=[0x85A13],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 5 Ammo Usage",
		addresses=[0x85A14],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 6 Ammo Usage",
		addresses=[0x85A15],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 7 Ammo Usage",
		addresses=[0x85A16],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 8 Ammo Usage",
		addresses=[0x85A17],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x0C,0x0B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Option Flag 1",
		addresses=[0x85A09],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Option Flag 2",
		addresses=[0x85A0B],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Option Flag 3",
		addresses=[0x85A0D],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Mode Flag",
		addresses=[0x85A19],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
]

"""
If you're using this file as a template, MAKE SURE YOU DELETE THESE RULES!
"""
Required_Rules = [
        Rule(
		description="No duplicate stage values",
		left_side=[value("1st stage"),value("2nd stage"),value("3rd stage"),value("4th stage"),
                           value("5th stage"),value("6th stage"),value("7th stage"),value("8th stage"),],
		rule_type="!=",
		right_side=None,
	),
         Rule(
		description="No duplicate Doc Robots Group 1",
		left_side=[value("Doc Robot 1 Programming"),value("Doc Robot 3 Programming"),
                           value("Doc Robot 5 Programming"),value("Doc Robot 7 Programming")],
		rule_type="!=",
		right_side=None,
	),
        Rule(
		description="No duplicate Doc Robots Group 2",
		left_side=[value("Doc Robot 2 Programming"),value("Doc Robot 4 Programming"),
                           value("Doc Robot 6 Programming"),value("Doc Robot 8 Programming")],
		rule_type="!=",
		right_side=None,
	),
        Rule(
		description="No duplicate Bosses",
		left_side=[value("Random Boss 1"),value("Random Boss 2"),value("Random Boss 8"),value("Random Boss 3"),
                           value("Random Boss 4"),value("Random Boss 5"),value("Random Boss 6"),value("Random Boss 7"),],
		rule_type="!=",
		right_side=None,
	),
        Rule(
		description="No duplicate Weapons",
		left_side=[value("Random Weapon 1"),value("Random Weapon 2"),value("Random Weapon 8"),value("Random Weapon 3"),
                           value("Random Weapon 4"),value("Random Weapon 5"),value("Random Weapon 6"),value("Random Weapon 7"),],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="Items can't be given out by same boss",
		left_side=[value("Rush Marine Flag"),value("Rush Jet Flag"),value("Item 3 Flag")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="2 Different weapons for Alien Weakness",
		left_side=[value("Alien Weakness 1"),value("Alien Weakness 2")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="3 different choices for bosses affected by Flash Stopper",
		left_side=[value("Boss affected by Flash Stopper 1"),value("Boss affected by Flash Stopper 2"),value("Boss affected by Flash Stopper 3")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="Weapons chosen to break walls can't be the same",
		left_side=[value("Random Weapon Breaks walls"),value("Random Weapon Breaks walls 2"),value("Random Weapon Breaks walls 3")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="No duplicate Bosses in Refights",
		left_side=[value("Sparkman Capsule"),value("Snakeman Capsule"),value("Needleman Capsule"),value("Hardman Capsule"),
                           value("Topman Capsule"),value("Geminiman Capsule"),value("Magnetman Capsule"),value("Shadowman Capsule"),],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="No more than 6 Deflects on Kamegoro Maker",
		left_side=[value("Kamegoro Maker Weakness 1"),value("Kamegoro Maker Weakness 2"),value("Kamegoro Maker Weakness 3"),value("Kamegoro Maker Weakness 4"),
                           value("Kamegoro Maker Weakness 5"),value("Kamegoro Maker Weakness 6"),value("Kamegoro Maker Weakness 7"),value("Kamegoro Maker Weakness 8"),],
		rule_type="count",
		right_side=("!=",0x82,"<=",6),
	),
        Rule(
		description="No more than 6 Deflects on Gamma 1",
		left_side=[value("Gamma 1 Weakness 1"),value("Gamma 1 Weakness 2"),value("Gamma 1 Weakness 3"),value("Gamma 1 Weakness 4"),
                           value("Gamma 1 Weakness 5"),value("Gamma 1 Weakness 6"),value("Gamma 1 Weakness 7"),value("Gamma 1 Weakness 8"),],
		rule_type="count",
		right_side=("!=",0x82,"<=",6),
	),
        Rule(
		description="No more than 6 Deflects on Gamma 2",
		left_side=[value("Gamma 2 Weakness 1"),value("Gamma 2 Weakness 2"),value("Gamma 2 Weakness 3"),value("Gamma 2 Weakness 4"),
                           value("Gamma 2 Weakness 5"),value("Gamma 2 Weakness 6"),value("Gamma 2 Weakness 7"),value("Gamma 2 Weakness 8"),],
		rule_type="count",
		right_side=("!=",0x82,"<=",6),
	),
]

"""
If you're using this file as a template, MAKE SURE YOU DELETE THESE RULESETS!
"""
Optional_Rulesets = [
        Ruleset(
		name="Randomize Bosses",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Flag 1"),
				rule_type="==",
				right_side=1,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 2"),
				rule_type="==",
				right_side=1,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 3"),
				rule_type="==",
				right_side=1,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 4"),
				rule_type="==",
				right_side=1,
			),
			Rule(
				description="Yes",
				left_side=value("Random Flag 5"),
				rule_type="==",
				right_side=1,
			),
                ],
			must_be_disabled=["Randomize Weapons","Randomize Bosses and Weapons"],
         ),

        Ruleset(
		name="Randomize Weapons",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Flag 1"),
				rule_type="==",
				right_side=2,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 2"),
				rule_type="==",
				right_side=2,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 3"),
				rule_type="==",
				right_side=2,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 4"),
				rule_type="==",
				right_side=2,
			),
			Rule(
				description="Yes",
				left_side=value("Random Flag 5"),
				rule_type="==",
				right_side=2,
			),

		],
		must_be_disabled=["Randomize Bosses","Randomize Bosses and Weapons"],
        ),

         Ruleset(
		name="Randomize Bosses and Weapons",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Flag 1"),
				rule_type="==",
				right_side=3,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 2"),
				rule_type="==",
				right_side=3,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 3"),
				rule_type="==",
				right_side=3,
			),
                        Rule(
				description="Yes",
				left_side=value("Random Flag 4"),
				rule_type="==",
				right_side=3,
			),
			Rule(
				description="Yes",
				left_side=value("Random Flag 5"),
				rule_type="==",
				right_side=3,
			),

		],
		must_be_disabled=["Randomize Bosses","Randomize Weapons"],
         ),
        
         Ruleset(
		name="Randomize Buster Damage to First 8 Bosses",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Option Flag 1"),
				rule_type="==",
				right_side=1,
			),
		],
		must_be_disabled=None,
         ),
        
         Ruleset(
		name="Randomize Damage from Bosses",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Option Flag 2"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
         ),

         Ruleset(
		name="Randomize Weapon Ammo Usage",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Option Flag 3"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
         ),
        Ruleset(
		name="Megaman 2 Mode",
		description="A set of basic rules",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Mode Flag"),
				rule_type="==",
				right_side=2,
			),

		],
		must_be_disabled=None,
         ),
]
