# This is a randomizer file for the Simple Randomizer Maker.
# This file must be named randomizer.py in order to work.

from classes import *

def value(name):
	for att in Attributes:
		if att.name == name:
			return att
	print("This attribute does not exist: "+name)
	return None

########################
# EDIT BELOW THIS LINE #
########################

Program_Name = "Megaman: Wily Wars Randomizer"
Rom_Name = "Megaman The Wily Wars"
Rom_File_Format = ""
About_Page_Text = "2021,2024 MaximumLance. Thanks to Runex, Matrixz, MottZilla, and GateGuy."
Timeout = 15
Slow_Mode = False

"""
If you're using this file as a template, MAKE SURE YOU DELETE THESE ATTRIBUTES!
"""
Attributes = [

        Attribute(
		name="1st stage",
		addresses=[0x644C2],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
	Attribute(
		name="2nd stage",
		addresses=[0x644C3],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="3rd stage",
		addresses=[0x644C4],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="4th stage",
		addresses=[0x644C5],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="5th stage",
		addresses=[0x644C6],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="6th stage",
		addresses=[0x644C7],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="7th stage",
		addresses=[0x644C8],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="8th stage",
		addresses=[0x644C9],
		number_of_bytes=1,
		possible_values=[0,1,2,3,4,5,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x28,0x29,0x2A,0x2B,0x2C,0x2D,0x2E,0x2F],
		min_value=None,
		max_value=None,
	),
 	Attribute(
                name="Doc Robot 1 Programming",
		addresses=[0x7B7F3],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD,0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 2 Programming",
		addresses=[0x7B8DF],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC,0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 3 Programming",
		addresses=[0x7BA41],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD,0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 4 Programming",
		addresses=[0x7BC11],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC,0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 5 Programming",
		addresses=[0x7BDF9],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD,0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 6 Programming",
		addresses=[0x7BF1B],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC,0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Robot 7 Programming",
		addresses=[0x7C0DB],
		number_of_bytes=1,
		possible_values=[0x7C,0xA9,0xAB,0xAD,0xA7,0xA8,0xAA,0xAC],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Robot 8 Programming",
		addresses=[0x7C1C7],
		number_of_bytes=1,
		possible_values=[0xA7,0xA8,0xAA,0xAC,0x7C,0xA9,0xAB,0xAD],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 1",
		addresses=[0x85810],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 2",
		addresses=[0x85811],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 3",
		addresses=[0x85812],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 4",
		addresses=[0x85813],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 5",
		addresses=[0x85814],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 6",
		addresses=[0x85815],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 7",
		addresses=[0x85816],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 1 Weakness 8",
		addresses=[0x85817],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 1 Weapon Weakness",
		addresses=[0x85818],
		number_of_bytes=1,
		min_value=2,
		max_value=8,
	),
	Attribute(
                name="Boss 1 Primary Weakness Damage",
		addresses=[0x85819],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 1 Weapon Weakness 2",
		addresses=[0x8581A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 1 Secondary Weakness Damage",
		addresses=[0x8581B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 1",
		addresses=[0x85820],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 2",
		addresses=[0x85821],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 3",
		addresses=[0x85822],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 4",
		addresses=[0x85823],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 5",
		addresses=[0x85824],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 6",
		addresses=[0x85825],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 7",
		addresses=[0x85826],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 2 Weakness 8",
		addresses=[0x85827],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 2 Weapon Weakness",
		addresses=[0x85828],
		number_of_bytes=1,
		possible_values=[1,3,4,5,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 2 Primary Weakness Damage",
		addresses=[0x85829],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 2 Weapon Weakness 2",
		addresses=[0x8582A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 2 Secondary Weakness Damage",
		addresses=[0x8582B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 3 Weakness 1",
		addresses=[0x85830],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 2",
		addresses=[0x85831],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 3",
		addresses=[0x85832],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 4",
		addresses=[0x85833],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 5",
		addresses=[0x85834],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 6",
		addresses=[0x85835],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 7",
		addresses=[0x85836],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 3 Weakness 8",
		addresses=[0x85837],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 3 Weapon Weakness",
		addresses=[0x85838],
		possible_values=[1,2,4,5,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 3 Primary Weakness Damage",
		addresses=[0x85839],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 3 Weapon Weakness 2",
		addresses=[0x8583A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 3 Secondary Weakness Damage",
		addresses=[0x8583B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 4 Weakness 1",
		addresses=[0x85840],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 2",
		addresses=[0x85841],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 3",
		addresses=[0x85842],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 4",
		addresses=[0x85843],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 5",
		addresses=[0x85844],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 6",
		addresses=[0x85845],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 7",
		addresses=[0x85846],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 4 Weakness 8",
		addresses=[0x85847],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 4 Weapon Weakness",
		addresses=[0x85848],
		number_of_bytes=1,
		possible_values=[1,2,3,5,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 4 Primary Weakness Damage",
		addresses=[0x85849],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 4 Weapon Weakness 2",
		addresses=[0x8584A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 4 Secondary Weakness Damage",
		addresses=[0x8584B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 5 Weakness 1",
		addresses=[0x85850],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 2",
		addresses=[0x85851],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 3",
		addresses=[0x85852],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 4",
		addresses=[0x85853],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 5",
		addresses=[0x85854],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 6",
		addresses=[0x85855],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 7",
		addresses=[0x85856],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 5 Weakness 8",
		addresses=[0x85857],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 5 Weapon Weakness",
		addresses=[0x85858],
		number_of_bytes=1,
		possible_values=[1,2,3,4,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 5 Primary Weakness Damage",
		addresses=[0x85859],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 5 Weapon Weakness 2",
		addresses=[0x8585A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 5 Secondary Weakness Damage",
		addresses=[0x8585B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 6 Weakness 1",
		addresses=[0x85860],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 2",
		addresses=[0x85861],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 3",
		addresses=[0x85862],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 4",
		addresses=[0x85863],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 5",
		addresses=[0x85864],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 6",
		addresses=[0x85865],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 7",
		addresses=[0x85866],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 6 Weakness 8",
		addresses=[0x85867],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 6 Weapon Weakness",
		addresses=[0x85868],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 6 Primary Weakness Damage",
		addresses=[0x85869],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 6 Weapon Weakness 2",
		addresses=[0x8586A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 6 Secondary Weakness Damage",
		addresses=[0x8586B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 7 Weakness 1",
		addresses=[0x85870],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 2",
		addresses=[0x85871],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 3",
		addresses=[0x85872],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 4",
		addresses=[0x85873],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 5",
		addresses=[0x85874],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 6",
		addresses=[0x85875],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 7",
		addresses=[0x85876],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 7 Weakness 8",
		addresses=[0x85877],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 7 Weapon Weakness",
		addresses=[0x85878],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 7 Primary Weakness Damage",
		addresses=[0x85879],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 7 Weapon Weakness 2",
		addresses=[0x8587A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 7 Secondary Weakness Damage",
		addresses=[0x8587B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Boss 8 Weakness 1",
		addresses=[0x85880],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 2",
		addresses=[0x85881],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 3",
		addresses=[0x85882],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 4",
		addresses=[0x85883],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 5",
		addresses=[0x85884],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 6",
		addresses=[0x85885],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 7",
		addresses=[0x85886],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Boss 8 Weakness 8",
		addresses=[0x85887],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 8 Weapon Weakness",
		addresses=[0x85888],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,7],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Boss 8 Primary Weakness Damage",
		addresses=[0x85889],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Boss 8 Weapon Weakness 2",
		addresses=[0x8588A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Boss 8 Secondary Weakness Damage",
		addresses=[0x8588B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 1",
		addresses=[0x85890],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 2",
		addresses=[0x85891],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 3",
		addresses=[0x85892],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 4",
		addresses=[0x85893],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 5",
		addresses=[0x85894],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 6",
		addresses=[0x85895],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 7",
		addresses=[0x85896],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 1 Weakness 8",
		addresses=[0x85897],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 1 Weapon Weakness",
		addresses=[0x85898],
		number_of_bytes=1,
		min_value=2,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 1 Primary Weakness Damage",
		addresses=[0x85899],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 1 Weapon Weakness 2",
		addresses=[0x8589A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 1 Secondary Weakness Damage",
		addresses=[0x8589B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 1",
		addresses=[0x858A0],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 2",
		addresses=[0x858A1],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 3",
		addresses=[0x858A2],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 4",
		addresses=[0x858A3],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 5",
		addresses=[0x858A4],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 6",
		addresses=[0x858A5],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 7",
		addresses=[0x858A6],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 2 Weakness 8",
		addresses=[0x858A7],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 2 Weapon Weakness",
		addresses=[0x858A8],
		number_of_bytes=1,
		possible_values=[1,3,4,5,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 2 Primary Weakness Damage",
		addresses=[0x858A9],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 2 Weapon Weakness 2",
		addresses=[0x858AA],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 2 Secondary Weakness Damage",
		addresses=[0x858AB],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 3 Weakness 1",
		addresses=[0x858B0],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 2",
		addresses=[0x858B1],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 3",
		addresses=[0x858B2],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 4",
		addresses=[0x858B3],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 5",
		addresses=[0x858B4],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 6",
		addresses=[0x858B5],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 7",
		addresses=[0x858B6],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 3 Weakness 8",
		addresses=[0x858B7],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 3 Weapon Weakness",
		addresses=[0x858B8],
		number_of_bytes=1,
		possible_values=[1,2,4,5,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 3 Primary Weakness Damage",
		addresses=[0x858B9],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 3 Weapon Weakness 2",
		addresses=[0x858BA],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 3 Secondary Weakness Damage",
		addresses=[0x858BB],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 4 Weakness 1",
		addresses=[0x858C0],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 2",
		addresses=[0x858C1],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 3",
		addresses=[0x858C2],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 4",
		addresses=[0x858C3],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 5",
		addresses=[0x858C4],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 6",
		addresses=[0x858C5],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 7",
		addresses=[0x858C6],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 4 Weakness 8",
		addresses=[0x858C7],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 4 Weapon Weakness",
		addresses=[0x858C8],
		number_of_bytes=1,
		possible_values=[1,2,3,5,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 4 Primary Weakness Damage",
		addresses=[0x858C9],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 4 Weapon Weakness 2",
		addresses=[0x858CA],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 4 Secondary Weakness Damage",
		addresses=[0x858CB],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 5 Weakness 1",
		addresses=[0x858D0],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 2",
		addresses=[0x858D1],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 3",
		addresses=[0x858D2],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 4",
		addresses=[0x858D3],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 5",
		addresses=[0x858D4],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 6",
		addresses=[0x858D5],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 7",
		addresses=[0x858D6],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 5 Weakness 8",
		addresses=[0x858D7],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 5 Weapon Weakness",
		addresses=[0x858D8],
		number_of_bytes=1,
		possible_values=[1,2,3,4,6,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 5 Primary Weakness Damage",
		addresses=[0x858D9],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 5 Weapon Weakness 2",
		addresses=[0x858DA],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 5 Secondary Weakness Damage",
		addresses=[0x858DB],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 6 Weakness 1",
		addresses=[0x858E0],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 2",
		addresses=[0x858E1],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 3",
		addresses=[0x858E2],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 4",
		addresses=[0x858E3],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 5",
		addresses=[0x858E4],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 6",
		addresses=[0x858E5],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 7",
		addresses=[0x858E6],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 6 Weakness 8",
		addresses=[0x858E7],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 6 Weapon Weakness",
		addresses=[0x858E8],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,7,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 6 Primary Weakness Damage",
		addresses=[0x858E9],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 6 Weapon Weakness 2",
		addresses=[0x858EA],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 6 Secondary Weakness Damage",
		addresses=[0x858EB],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 7 Weakness 1",
		addresses=[0x858F0],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 2",
		addresses=[0x858F1],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 3",
		addresses=[0x858F2],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 4",
		addresses=[0x858F3],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 5",
		addresses=[0x858F4],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 6",
		addresses=[0x858F5],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 7",
		addresses=[0x858F6],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 7 Weakness 8",
		addresses=[0x858F7],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 7 Weapon Weakness",
		addresses=[0x858F8],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 7 Primary Weakness Damage",
		addresses=[0x858F9],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 7 Weapon Weakness 2",
		addresses=[0x858FA],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 7 Secondary Weakness Damage",
		addresses=[0x858FB],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
           Attribute(
                name="Doc Boss 8 Weakness 1",
		addresses=[0x85900],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 2",
		addresses=[0x85901],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 3",
		addresses=[0x85902],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 4",
		addresses=[0x85903],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 5",
		addresses=[0x85904],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 6",
		addresses=[0x85905],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 7",
		addresses=[0x85906],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Doc Boss 8 Weakness 8",
		addresses=[0x85907],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Doc Boss 8 Weapon Weakness",
		addresses=[0x85908],
		number_of_bytes=1,
		min_value=1,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 8 Primary Weakness Damage",
		addresses=[0x85909],
		number_of_bytes=1,
		min_value=6,
		max_value=7,
	),
	Attribute(
                name="Doc Boss 8 Weapon Weakness 2",
		addresses=[0x8590A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Doc Boss 8 Secondary Weakness Damage",
		addresses=[0x8590B],
		number_of_bytes=1,
		possible_values=[4],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 1",
		addresses=[0x85910],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 2",
		addresses=[0x85911],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 3",
		addresses=[0x85912],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 4",
		addresses=[0x85913],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 5",
		addresses=[0x85914],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 6",
		addresses=[0x85915],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 7",
		addresses=[0x85916],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Kamegoro Maker Weakness 8",
		addresses=[0x85917],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Kamegoro Weapon Weakness",
		addresses=[0x85918],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Kamegoro Weapon Weakness 2",
		addresses=[0x85919],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
           Attribute(
                name="Yellow Devil Mk-3 Weakness 1",
		addresses=[0x85920],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 2",
		addresses=[0x85921],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 3",
		addresses=[0x85922],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 4",
		addresses=[0x85923],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 5",
		addresses=[0x85924],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 6",
		addresses=[0x85925],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 7",
		addresses=[0x85926],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Yellow Devil Mk-3 Weakness 8",
		addresses=[0x85927],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Yellow Devil Mk-3 Weapon Weakness",
		addresses=[0x85928],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Yellow Devil Mk-3 Weakness Damage",
		addresses=[0x85929],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Yellow Devil Mk-3 Weakness 2",
		addresses=[0x8592A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Yellow Devil Mk-3 Weakness Damage 2",
		addresses=[0x8592B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
           Attribute(
                name="Holograph Megamans Weakness 1",
		addresses=[0x85930],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 2",
		addresses=[0x85931],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 3",
		addresses=[0x85932],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 4",
		addresses=[0x85933],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 5",
		addresses=[0x85934],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 6",
		addresses=[0x85935],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 7",
		addresses=[0x85936],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Holograph Megamans Weakness 8",
		addresses=[0x85937],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Holograph Megamans Weakness",
		addresses=[0x85938],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Holograph Megamans Weakness Damage",
		addresses=[0x85939],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Holograph Megamans Weakness 2",
		addresses=[0x8593A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Holograph Megamans Weakness Damage 2",
		addresses=[0x8593B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
           Attribute(
                name="Wily Machine 3 Weakness 1",
		addresses=[0x85940],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 2",
		addresses=[0x85941],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 3",
		addresses=[0x85942],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 4",
		addresses=[0x85943],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 5",
		addresses=[0x85944],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 6",
		addresses=[0x85945],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 7",
		addresses=[0x85946],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Machine 3 Weakness 8",
		addresses=[0x85947],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Wily Machine 3 Weakness",
		addresses=[0x85948],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Machine 3 Weakness Damage",
		addresses=[0x85949],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Wily Machine 3 Weakness 2",
		addresses=[0x8594A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Machine 3 Weakness Damage 2",
		addresses=[0x8594B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
           Attribute(
                name="Gamma 1 Weakness 1",
		addresses=[0x85960],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 2",
		addresses=[0x85961],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 3",
		addresses=[0x85962],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 4",
		addresses=[0x85963],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 5",
		addresses=[0x85964],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 6",
		addresses=[0x85965],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 7",
		addresses=[0x85966],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 1 Weakness 8",
		addresses=[0x85967],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Gamma 1 Weapon Weakness",
		addresses=[0x85968],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Gamma 1 Weapon Weakness 2",
		addresses=[0x85969],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
           Attribute(
                name="Gamma 2 Weakness 1",
		addresses=[0x85970],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 2",
		addresses=[0x85971],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 3",
		addresses=[0x85972],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 4",
		addresses=[0x85973],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 5",
		addresses=[0x85974],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 6",
		addresses=[0x85975],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 7",
		addresses=[0x85976],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Gamma 2 Weakness 8",
		addresses=[0x85977],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Gamma 2 Weapon Weakness",
		addresses=[0x85978],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Gamma 2 Weapon Weakness 2",
		addresses=[0x85979],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Boobeam Weakness 2",
		addresses=[0x85981],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Alien Weakness 1",
		addresses=[0x85982],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Alien Weakness 2",
		addresses=[0x85983],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 1 Weakness 1",
		addresses=[0x85C00],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 2",
		addresses=[0x85C01],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 3",
		addresses=[0x85C02],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 4",
		addresses=[0x85C03],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 5",
		addresses=[0x85C04],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 6",
		addresses=[0x85C05],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 7",
		addresses=[0x85C06],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 1 Weakness 8",
		addresses=[0x85C07],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Wily Boss 1 Weakness",
		addresses=[0x85C08],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 1 Weakness Damage",
		addresses=[0x85C09],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Wily Boss 1 Weakness 2",
		addresses=[0x85C0A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 1 Weakness Damage 2",
		addresses=[0x85C0B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
           Attribute(
                name="Wily Boss 2 Weakness 1",
		addresses=[0x85C10],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 2",
		addresses=[0x85C11],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 3",
		addresses=[0x85C12],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 4",
		addresses=[0x85C13],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 5",
		addresses=[0x85C14],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 6",
		addresses=[0x85C15],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 7",
		addresses=[0x85C16],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 2 Weakness 8",
		addresses=[0x85C17],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Wily Boss 2 Weakness",
		addresses=[0x85C18],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 2 Weakness Damage",
		addresses=[0x85C19],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Wily Boss 2 Weakness 2",
		addresses=[0x85C1A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 2 Weakness Damage 2",
		addresses=[0x85C1B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
        Attribute(
                name="Wily Boss 3 Weakness 1",
		addresses=[0x85C20],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 2",
		addresses=[0x85C21],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 3",
		addresses=[0x85C22],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 4",
		addresses=[0x85C23],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 5",
		addresses=[0x85C24],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 6",
		addresses=[0x85C25],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 7",
		addresses=[0x85C26],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 3 Weakness 8",
		addresses=[0x85C27],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Wily Boss 3 Weakness",
		addresses=[0x85C28],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 3 Weakness Damage",
		addresses=[0x85C29],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Wily Boss 3 Weakness 2",
		addresses=[0x85C2A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 3 Weakness Damage 2",
		addresses=[0x85C2B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
           Attribute(
                name="Wily Boss 4 Weakness 1",
		addresses=[0x85C30],
		number_of_bytes=1,
                possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 2",
		addresses=[0x85C31],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 3",
		addresses=[0x85C32],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 4",
		addresses=[0x85C33],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 5",
		addresses=[0x85C34],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 6",
		addresses=[0x85C35],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 7",
		addresses=[0x85C36],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Wily Boss 4 Weakness 8",
		addresses=[0x85C37],
		number_of_bytes=1,
		possible_values=[1,2],
		min_value=None,
		max_value=None,
	),
	Attribute(
                name="Wily Boss 4 Weakness",
		addresses=[0x85C38],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 4 Weakness Damage",
		addresses=[0x85C39],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
	Attribute(
                name="Wily Boss 4 Weakness 2",
		addresses=[0x85C3A],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 4 Weakness Damage 2",
		addresses=[0x85C3B],
		number_of_bytes=1,
		min_value=4,
		max_value=6,
	),
        Attribute(
                name="Random Boss 1",
		addresses=[0x85990],
		number_of_bytes=1,
                possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 2",
		addresses=[0x85991],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 3",
		addresses=[0x85992],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 4",
		addresses=[0x85993],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 5",
		addresses=[0x85994],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 6",
		addresses=[0x85995],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 7",
		addresses=[0x85996],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Boss 8",
		addresses=[0x85997],
		number_of_bytes=1,
		possible_values=[0x14,0x15,0x16,0x17,0x18,0x19,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x74,0x75,0x76,0x77,0x78,0x79,0x7A,0x7B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 1",
		addresses=[0x859A0],
		number_of_bytes=1,
                possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 2",
		addresses=[0x859A1],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 3",
		addresses=[0x859A2],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 4",
		addresses=[0x859A3],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 5",
		addresses=[0x859A4],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 6",
		addresses=[0x859A5],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 7",
		addresses=[0x859A6],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Weapon 8",
		addresses=[0x859A7],
		number_of_bytes=1,
		possible_values=[1,2,3,4,5,6,8,9,0xA,0xB,0xC,0xE,0xF,0x10,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Wily Stage 1",
		addresses=[0x857FA],
		number_of_bytes=1,
		possible_values=[6,7,8,0x1C,0x1D,0x1E,0x1F,0x35,0x36,0x37,0x39],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Wily Stage 2",
		addresses=[0x857FB],
		number_of_bytes=1,
		possible_values=[6,7,8,0x1C,0x1D,0x1E,0x1F,0x35,0x36,0x37,0x39],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Wily Stage 3",
		addresses=[0x857FC],
		number_of_bytes=1,
		possible_values=[6,7,8,0x1C,0x1D,0x1E,0x1F,0x35,0x36,0x37,0x39],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Wily Stage 4",
		addresses=[0x857FD],
		number_of_bytes=1,
		possible_values=[6,7,8,0x1C,0x1D,0x1E,0x1F,0x35,0x36,0x37,0x39],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Wily Stage 5",
		addresses=[0x857FE],
		number_of_bytes=1,
		possible_values=[0x20,0x38],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Wily Stage 6",
		addresses=[0x857FF],
		number_of_bytes=1,
		possible_values=[9,0x21,0x3A],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Random Mode Flag",
		addresses=[0x85800],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Rush Marine Flag",
		addresses=[0x85805],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Rush Jet Flag",
		addresses=[0x85806],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Item 3 Flag",
		addresses=[0x8580D],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Sparkman Capsule",
		addresses=[0x859B0],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Snakeman Capsule",
		addresses=[0x859B1],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Needleman Capsule",
		addresses=[0x859B2],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Hardman Capsule",
		addresses=[0x859B3],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Topman Capsule",
		addresses=[0x859B4],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Geminiman Capsule",
		addresses=[0x859B5],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Magnetman Capsule",
		addresses=[0x859B6],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Shadowman Capsule",
		addresses=[0x859B7],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
         Attribute(
                name="Random Weapon Breaks walls",
		addresses=[0x85807],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Random Weapon Breaks walls 2",
		addresses=[0x85808],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Random Weapon Breaks walls 3",
		addresses=[0x85809],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 1 Collision Damage",
		addresses=[0x859C0],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 2 Collision Damage",
		addresses=[0x859C1],
                number_of_bytes=1,
                min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 3 Collision Damage",
		addresses=[0x859C2],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 4 Collision Damage",
		addresses=[0x859C3],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 5 Collision Damage",
		addresses=[0x859C4],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 6 Collision Damage",
		addresses=[0x859C5],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 7 Collision Damage",
		addresses=[0x859C6],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 8 Collision Damage",
		addresses=[0x859C7],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 9 Collision Damage",
		addresses=[0x859C8],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="MM1 Boss 1 Collision Damage",
		addresses=[0x859C9],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 2 Collision Damage",
		addresses=[0x859CA],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 3 Collision Damage",
		addresses=[0x859CB],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 4 Collision Damage",
		addresses=[0x859CC],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 5 Collision Damage",
		addresses=[0x859CD],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 6 Collision Damage",
		addresses=[0x859CE],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 1 Collision Damage",
		addresses=[0x859D0],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 2 Collision Damage",
		addresses=[0x859D1],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 3 Collision Damage",
		addresses=[0x859D2],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 4 Collision Damage",
		addresses=[0x859D3],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 5 Collision Damage",
		addresses=[0x859D4],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 6 Collision Damage",
		addresses=[0x859D5],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 7 Collision Damage",
		addresses=[0x859D6],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 8 Collision Damage",
		addresses=[0x859D7],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Metal Collision Damage",
		addresses=[0x859D8],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Heat Collision Damage",
		addresses=[0x859D9],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Quick Collision Damage",
		addresses=[0x859DA],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Air Collision Damage",
		addresses=[0x859DB],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Crash Collision Damage",
		addresses=[0x859DC],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Flash Collision Damage",
		addresses=[0x859DD],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Bubble Collision Damage",
		addresses=[0x859DE],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Wood Collision Damage",
		addresses=[0x859DF],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Breakman Collision Damage",
		addresses=[0x859E0],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Boss 1 Weapon Damage",
		addresses=[0x859F0],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 2 Weapon Damage",
		addresses=[0x859F1],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 3 Weapon Damage",
		addresses=[0x859F2],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 4 Weapon Damage",
		addresses=[0x859F3],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 5 Weapon Damage",
		addresses=[0x859F4],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 6 Weapon Damage",
		addresses=[0x859F5],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 7 Weapon Damage",
		addresses=[0x859F6],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Boss 8 Weapon Damage",
		addresses=[0x859F7],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Doc Metal Weapon Damage",
		addresses=[0x859F8],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Heat Weapon Damage",
		addresses=[0x859F9],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Quick Weapon Damage",
		addresses=[0x859FA],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Air Weapon Damage",
		addresses=[0x859FB],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Crash Weapon Damage",
		addresses=[0x859FC],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Bubble Weapon Damage",
		addresses=[0x859FD],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Doc Wood Weapon Damage",
		addresses=[0x859FE],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Breakman Weapon Damage",
		addresses=[0x859FF],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Wily Boss 1 Weapon Damage",
		addresses=[0x85A00],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 2 Weapon Damage",
		addresses=[0x85A01],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 3 Weapon Damage",
		addresses=[0x85A02],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 4 Weapon Damage",
		addresses=[0x85A03],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 5 Weapon Damage",
		addresses=[0x85A04],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 6 Weapon Damage",
		addresses=[0x85A05],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 7 Weapon Damage",
		addresses=[0x85A06],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 8 Weapon Damage",
		addresses=[0x85A07],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
        Attribute(
                name="Wily Boss 9 Weapon Damage",
		addresses=[0x85A08],
                number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="MM1 Boss 1 Weapon Damage",
		addresses=[0x85A09],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 2 Weapon Damage",
		addresses=[0x85A0A],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 3 Weapon Damage",
		addresses=[0x85A0B],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 4 Weapon Damage",
		addresses=[0x85A0C],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 5 Weapon Damage",
		addresses=[0x85A0D],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="MM1 Boss 6 Weapon Damage",
		addresses=[0x85A0E],
                number_of_bytes=1,
		min_value=1,
		max_value=6,
	),
        Attribute(
                name="Weapon 1 Ammo Usage",
		addresses=[0x85A10],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 2 Ammo Usage",
		addresses=[0x85A11],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 3 Ammo Usage",
		addresses=[0x85A12],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 4 Ammo Usage",
		addresses=[0x85A13],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 5 Ammo Usage",
		addresses=[0x85A14],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 6 Ammo Usage",
		addresses=[0x85A15],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 7 Ammo Usage",
		addresses=[0x85A16],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Weapon 8 Ammo Usage",
		addresses=[0x85A17],
                number_of_bytes=1,
		possible_values=[0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,0x11,0x12],
		min_value=None,
		max_value=None,
	),
        Attribute(
                name="Mode Flag",
		addresses=[0x85A19],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Random Wily Flag",
		addresses=[0x85A1C],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Castle Intro Skip Flag",
		addresses=[0x85A1E],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
	Attribute(
                name="No Lives Refill Flag",
		addresses=[0x85A20],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Time Stopper Stopper Flag",
		addresses=[0x85A22],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
	Attribute(
                name="Random Weapon freezes Fire Tower",
		addresses=[0x85A24],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Random Weapon freezes Fire Tower 2",
		addresses=[0x85A25],
		number_of_bytes=1,
		min_value=1,
		max_value=8,
	),
	Attribute(
                name="Weapon Balancer Mod Flag",
		addresses=[0x85A26],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Random Damage Flag",
		addresses=[0x85A28],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
        Attribute(
                name="Random Ammo Flag", #Don't add anything else past this memory address
		addresses=[0x85A2A],
		number_of_bytes=2,
		min_value=0,
		max_value=65535,
	),
]

"""
If you're using this file as a template, MAKE SURE YOU DELETE THESE RULES!
"""
Required_Rules = [
        Rule(
		description="No duplicate stage values",
		left_side=[value("1st stage"),value("2nd stage"),value("3rd stage"),value("4th stage"),
                           value("5th stage"),value("6th stage"),value("7th stage"),value("8th stage"),],
		rule_type="!=",
		right_side=None,
	),
         Rule(
		description="No duplicate Doc Robots",
		left_side=[value("Doc Robot 1 Programming"),value("Doc Robot 3 Programming"),
                           value("Doc Robot 5 Programming"),value("Doc Robot 7 Programming"),
                           value("Doc Robot 2 Programming"),value("Doc Robot 4 Programming"),
                           value("Doc Robot 6 Programming"),value("Doc Robot 8 Programming")],
		rule_type="!=",
		right_side=None,
	),
        Rule(
		description="No duplicate Bosses",
		left_side=[value("Random Boss 1"),value("Random Boss 2"),value("Random Boss 8"),value("Random Boss 3"),
                           value("Random Boss 4"),value("Random Boss 5"),value("Random Boss 6"),value("Random Boss 7"),],
		rule_type="!=",
		right_side=None,
	),
        Rule(
		description="No duplicate Weapons",
		left_side=[value("Random Weapon 1"),value("Random Weapon 2"),value("Random Weapon 8"),value("Random Weapon 3"),
                           value("Random Weapon 4"),value("Random Weapon 5"),value("Random Weapon 6"),value("Random Weapon 7"),],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="No duplicate Wily Stages",
		left_side=[value("Random Wily Stage 1"),value("Random Wily Stage 2"),
                           value("Random Wily Stage 3"),value("Random Wily Stage 4")],
		rule_type="!=",
		right_side=None,
	),
        Rule(
		description="Items can't be given out by same boss",
		left_side=[value("Rush Marine Flag"),value("Rush Jet Flag"),value("Item 3 Flag")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="2 Different weapons for Alien Weakness",
		left_side=[value("Alien Weakness 1"),value("Alien Weakness 2")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="Weapons chosen to break walls can't be the same",
		left_side=[value("Random Weapon Breaks walls"),value("Random Weapon Breaks walls 2"),value("Random Weapon Breaks walls 3")],
		rule_type="!=",
		right_side=None,

	),
        Rule(
		description="No duplicate Bosses in Refights",
		left_side=[value("Sparkman Capsule"),value("Snakeman Capsule"),value("Needleman Capsule"),value("Hardman Capsule"),
                           value("Topman Capsule"),value("Geminiman Capsule"),value("Magnetman Capsule"),value("Shadowman Capsule"),],
		rule_type="!=",
		right_side=None,

	),
	Rule(
		description="2 different choices for weapon that freezes Fire Towers",
		left_side=[value("Random Weapon freezes Fire Tower"),value("Random Weapon freezes Fire Tower 2"),],
		rule_type="!=",
		right_side=None,

	),
	Rule(
		description="1 unique weapon weakness for each boss",
		left_side=[value("Boss 1 Weapon Weakness"),value("Boss 2 Weapon Weakness"),value("Boss 3 Weapon Weakness"),value("Boss 4 Weapon Weakness"),
                           value("Boss 5 Weapon Weakness"),value("Boss 6 Weapon Weakness"),value("Boss 7 Weapon Weakness"),value("Boss 8 Weapon Weakness"),],
		rule_type="!=",
		right_side=None,

	),
	Rule(
		description="1 unique weapon weakness for each doc robot",
		left_side=[value("Doc Boss 1 Weapon Weakness"),value("Doc Boss 2 Weapon Weakness"),value("Doc Boss 3 Weapon Weakness"),value("Doc Boss 4 Weapon Weakness"),
                           value("Doc Boss 5 Weapon Weakness"),value("Doc Boss 6 Weapon Weakness"),value("Doc Boss 7 Weapon Weakness"),value("Doc Boss 8 Weapon Weakness"),],
		rule_type="!=",
		right_side=None,

	),
]

"""
If you're using this file as a template, MAKE SURE YOU DELETE THESE RULESETS!
"""
Optional_Rulesets = [
        Ruleset(
		name="Randomize Bosses Only",
		description="First 8 stages will be randomized and contain a random boss. Leave this unchecked if you want Random Bosses and Weapons.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Mode Flag"),
				rule_type="==",
				right_side=1,
			),
                ],
			must_be_disabled=["Randomize Weapons Only","Randomize Stages Only"],
         ),

        Ruleset(
		name="Randomize Weapons Only",
		description="First 8 stages will be randomized and each boss will give a different weapon than their normal one. Leave this unchecked if you want Random Bosses and Weapons.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Mode Flag"),
				rule_type="==",
				right_side=2,
			),
		],
		must_be_disabled=["Randomize Bosses Only","Randomize Stages Only"],
        ),

         Ruleset(
		name="Randomize Stages Only",
		description="First 8 stages will be randomized. Leave this unchecked if you want Random Bosses and Weapons.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Mode Flag"),
				rule_type="==",
				right_side=3,
			),
		],
		must_be_disabled=["Randomize Bosses Only","Randomize Weapons Only"],
         ),
        
         Ruleset(
		name="Randomize Damage from Bosses",
		description="Randomize their weapon and collision damage",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Damage Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
         ),

         Ruleset(
		name="Randomize Weapon Ammo Usage",
		description="Randomizes how much ammo your weapons will use",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Ammo Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
         ),
        Ruleset(
		name="Megaman 2 Mode",
		description="Click this to enable Megaman 2 randomizer mode. Default is Megaman 3.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Mode Flag"),
				rule_type="==",
				right_side=2,
			),

		],
		must_be_disabled=None,
         ),
        Ruleset(
		name="Randomize Wily Stages",
		description="The 6 Wily Stages will be randomized from different games",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Random Wily Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
         ),
        Ruleset(
		name="Skip Castle Intro",
		description="The castle map intro will not be shown. You will immediately go to the next Wily Stage.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Castle Intro Skip Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
        ),
        Ruleset(
		name="Disable Lives Refill",
		description="New default is lives are refilled if they are less than 2 after completing a stage.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("No Lives Refill Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
        ),
        Ruleset(
		name="Disable Time Stopper Mod",
		description="New default is Time Stopper will stop after only a few weapon energy has been used. This reverts it back to normal.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Time Stopper Stopper Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
        ),
        Ruleset(
		name="Disable Energy Balancer Mod",
		description="By default, weapon energy you pick up with no weapon selected will refill your lowest weapon energy. Check this to disable this.",
		rules=[
			Rule(
				description="Yes",
				left_side=value("Weapon Balancer Mod Flag"),
				rule_type="==",
				right_side=1,
			),

		],
		must_be_disabled=None,
        ),
]
